# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spiritvpn.customer.v1 import customer_pb2 as spiritvpn_dot_customer_dot_v1_dot_customer__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spiritvpn/customer/v1/customer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerAccessServiceStub:
    """CustomerAccessService — единственная внешняя командно-запросная поверхность для
    customer access. Всё состояние, которое он меняет, durable в PostgreSQL до
    возврата ответа.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyCustomerAccess = channel.unary_unary(
                '/spiritvpn.customer.v1.CustomerAccessService/ApplyCustomerAccess',
                request_serializer=spiritvpn_dot_customer_dot_v1_dot_customer__pb2.ApplyCustomerAccessRequest.SerializeToString,
                response_deserializer=spiritvpn_dot_customer_dot_v1_dot_customer__pb2.ApplyCustomerAccessResponse.FromString,
                _registered_method=True)
        self.GetCustomerAccessLinks = channel.unary_unary(
                '/spiritvpn.customer.v1.CustomerAccessService/GetCustomerAccessLinks',
                request_serializer=spiritvpn_dot_customer_dot_v1_dot_customer__pb2.GetCustomerAccessLinksRequest.SerializeToString,
                response_deserializer=spiritvpn_dot_customer_dot_v1_dot_customer__pb2.GetCustomerAccessLinksResponse.FromString,
                _registered_method=True)


class CustomerAccessServiceServicer:
    """CustomerAccessService — единственная внешняя командно-запросная поверхность для
    customer access. Всё состояние, которое он меняет, durable в PostgreSQL до
    возврата ответа.
    """

    def ApplyCustomerAccess(self, request, context):
        """Идемпотентное создание/продление/смена квоты доступа customer к одному fleet.
        Порядок и защита от повторов — через command_number. Успешный ответ
        означает, что desired state зафиксирован, а НЕ что агенты уже применили его.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomerAccessLinks(self, request, context):
        """Возвращает все текущие (не retired) access customer с состоянием ссылки и
        готовую VLESS URI только для READY. Ответ с URI не кешируется и не
        логируется.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerAccessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyCustomerAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyCustomerAccess,
                    request_deserializer=spiritvpn_dot_customer_dot_v1_dot_customer__pb2.ApplyCustomerAccessRequest.FromString,
                    response_serializer=spiritvpn_dot_customer_dot_v1_dot_customer__pb2.ApplyCustomerAccessResponse.SerializeToString,
            ),
            'GetCustomerAccessLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomerAccessLinks,
                    request_deserializer=spiritvpn_dot_customer_dot_v1_dot_customer__pb2.GetCustomerAccessLinksRequest.FromString,
                    response_serializer=spiritvpn_dot_customer_dot_v1_dot_customer__pb2.GetCustomerAccessLinksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spiritvpn.customer.v1.CustomerAccessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spiritvpn.customer.v1.CustomerAccessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerAccessService:
    """CustomerAccessService — единственная внешняя командно-запросная поверхность для
    customer access. Всё состояние, которое он меняет, durable в PostgreSQL до
    возврата ответа.
    """

    @staticmethod
    def ApplyCustomerAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiritvpn.customer.v1.CustomerAccessService/ApplyCustomerAccess',
            spiritvpn_dot_customer_dot_v1_dot_customer__pb2.ApplyCustomerAccessRequest.SerializeToString,
            spiritvpn_dot_customer_dot_v1_dot_customer__pb2.ApplyCustomerAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomerAccessLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiritvpn.customer.v1.CustomerAccessService/GetCustomerAccessLinks',
            spiritvpn_dot_customer_dot_v1_dot_customer__pb2.GetCustomerAccessLinksRequest.SerializeToString,
            spiritvpn_dot_customer_dot_v1_dot_customer__pb2.GetCustomerAccessLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
